version: 2.1

commands:
  install-and-configure-host-dependencies:
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y qemu-utils libvirt-bin libvirt-dev libguestfs-tools python3-lxml python3-libvirt virtinst
      - run: echo 'libvirtd_opts="-l -f /etc/libvirt/libvirtd.conf"' | sudo tee -a /etc/default/libvirtd
      - run: sudo bash -c 'cat ${LIBVIRTD_CONF} >> /etc/libvirt/libvirtd.conf'
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: go get github.com/mitchellh/gox
  run-unit-tests:
    steps:
      - run: |
          docker run \
          --user root \
          --privileged \
          --net host \
          -v /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock \
          -v $PWD:/go/src/github.com/mahakamcloud/netd \
          -w /go/src/github.com/mahakamcloud/netd \
          -e GOCOVMODE=atomic \
          -e CODECOV_TOKEN=$CODECOV_TOKEN \
          mahakamcloud/maha-cross:v0.1.0-3 \
          bash -c 'yum install libvirt-devel gcc -y && dep ensure -v && go get -u github.com/axw/gocov/gocov && go get -u gopkg.in/matm/v1/gocov-html && ./hack/test.sh && bash <(curl -s https://codecov.io/bash)'
  create-release:
    steps:
      - run: cd /home/circleci
      - run: mkdir -p pkg src/github.com/mahakamcloud/netd
      - run: mv project/* src/github.com/mahakamcloud/netd/
      - run: export GOPATH=$GOPATH:/home/circleci/
      - run: dep ensure
      - run: gox -os="linux" -arch="amd64" -output="dist/netd_{{.OS}}_{{.Arch}}"
  publish-release:
    steps:
      - run: cd /home/circleci/src/github.com/mahakamcloud/netd
      - run: go get github.com/tcnksm/ghr
      - run: ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./dist/


jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-and-configure-host-dependencies
      - run-unit-tests
  publish-github-release:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - install-and-configure-host-dependencies
      - create-release
      - publish-release

workflows:
  version: 2
  main:
    jobs:
      - build:
          filter:
            tags:
              only: /.*/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
