version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: 
          name: Install and configure host dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y qemu-utils libvirt-bin libvirt-dev libguestfs-tools python3-lxml python3-libvirt virtinst

            echo 'libvirtd_opts="-l -f /etc/libvirt/libvirtd.conf"' | sudo tee -a /etc/default/libvirtd

            sudo bash -c 'cat <<EOL >> /etc/libvirt/libvirtd.conf
            listen_tls = 0
            listen_tcp = 1
            auth_tcp = "none"
            EOL'

            sudo systemctl restart libvirtd.service
      - run:
          name: Run unit tests
          command: |
            # TODO(giri): need to build new image that has remaining deps
            docker run \
              --user root \
              --privileged \
              --net host \
              -v /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock \
              -v $PWD:/go/src/github.com/mahakamcloud/netd \
              -w /go/src/github.com/mahakamcloud/netd \
              -e GOCOVMODE=atomic \
              -e CODECOV_TOKEN=$CODECOV_TOKEN \
              mahakamcloud/maha-cross:v0.1.0-3 \
              bash -c 'yum install libvirt-devel gcc -y && dep ensure -v && go get -u github.com/axw/gocov/gocov && go get -u gopkg.in/matm/v1/gocov-html && ./hack/test.sh && bash <(curl -s https://codecov.io/bash)'
          no_output_timeout: 30m
