version: 2
jobs:
  build:
    working_directory: /go/src/github.com/mahakamcloud/netd
    docker:
      - image: mahakamcloud/builder:20190219
    steps:
      - checkout

      - run:
          name: Run unit tests
          command: make localtest
          no_output_timeout: 30m
